# Generated by Django 4.1.7 on 2023-02-21 10:15

import DjangoPetstagram.photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_create_photo_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='media_files/photo_app', validators=[DjangoPetstagram.photos.models.check_file_size_5mb]),
        ),
    ]
