# Generated by Django 4.1.7 on 2023-03-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('photo',)},
        ),
    ]
