# Generated by Django 4.1.7 on 2023-03-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_photo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-date_of_publication',)},
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_of_publication',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
