# Generated by Django 4.1.7 on 2023-03-15 15:29

import DjangoPetstagram.accounts.models
import DjangoPetstagram.accounts.validators
import DjangoPetstagram.photos.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.MinLengthValidator(2), DjangoPetstagram.accounts.validators.check_alphabetical_letters]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('DoNotShow', 'Do not show')], default=DjangoPetstagram.accounts.models.GenderEnum['DoNotShow'], max_length=11),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.MinLengthValidator(2), DjangoPetstagram.accounts.validators.check_alphabetical_letters]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='media_files/accounts_app', validators=[DjangoPetstagram.photos.validators.check_file_size_5mb]),
        ),
    ]
